### PR TITLE
add new options showIndex, showChildCount

### PR DESCRIPTION
**Pull request by muescha**
changes:

- add new Options
- add more examples

this is helpful if some difflines is interesting:

```javascript
var inspectOptions = {
                       showPositions: false, 
                       showIndex: false, 
                       showChildCount: false
                     }
let resultUnistInspect = require("diff").diffLines(
    inspect(before, inspectOptions), 
    inspect(tree,inspectOptions)
)
```

### CODE REVIEW

**Comment by muescha** [comment]
reduces diff noise from:


```diff
- │   └─2 SentenceNode[29] (397:110-397:197, 13416-13503)
- 
+ │   └─2 SentenceNode[28] (397:110-397:197, 13416-13503)
+ 
  │       ├─0 WordNode[1] (397:110-397:114, 13416-13420)
  │       │   └─0 TextNode "Make" (397:110-397:114, 13416-13420)
  │       ├─1 WhiteSpaceNode " " (397:114-397:115, 13420-13421)
  │       ├─2 WordNode[1] (397:115-397:119, 13421-13425)
  │       │   └─0 TextNode "sure" (397:115-397:119, 13421-13425)
  │       ├─3 WhiteSpaceNode " " (397:119-397:120, 13425-13426)
  │       ├─4 WordNode[1] (397:120-397:122, 13426-13428)
  │       │   └─0 TextNode "to" (397:120-397:122, 13426-13428)
  │       ├─5 WhiteSpaceNode " " (397:122-397:123, 13428-13429)
  │       ├─6 WordNode[1] (397:123-397:130, 13429-13436)
  │       │   └─0 TextNode "mention" (397:123-397:130, 13429-13436)
  │       ├─7 WhiteSpaceNode " " (397:130-397:131, 13436-13437)
  
- │       ├─8 SymbolNode "@" (397:131-397:132, 13437-13438)
- │       ├─9 WordNode[1] (397:132-397:140, 13438-13446)
- │       │   └─0 TextNode "gatsbyjs" (397:132-397:140, 13438-13446)
- │       ├─10 WhiteSpaceNode " " (397:140-397:141, 13446-13447)
- │       ├─11 WordNode[1] (397:141-397:143, 13447-13449)
- 
+ │       ├─8 SourceNode "@gatsbyjs" (397:131-397:140, 13437-13446)
+ │       ├─9 WhiteSpaceNode " " (397:140-397:141, 13446-13447)
+ │       ├─10 WordNode[1] (397:141-397:143, 13447-13449)
+ 
  │       │   └─0 TextNode "in" (397:141-397:143, 13447-13449)
  
- │       ├─12 WhiteSpaceNode " " (397:143-397:144, 13449-13450)
- │       ├─13 WordNode[1] (397:144-397:148, 13450-13454)
- 
+ │       ├─11 WhiteSpaceNode " " (397:143-397:144, 13449-13450)
+ │       ├─12 WordNode[1] (397:144-397:148, 13450-13454)
+ 
  │       │   └─0 TextNode "your" (397:144-397:148, 13450-13454)
  
- │       ├─14 WhiteSpaceNode " " (397:148-397:149, 13454-13455)
- │       ├─15 WordNode[1] (397:149-397:154, 13455-13460)
- 
+ │       ├─13 WhiteSpaceNode " " (397:148-397:149, 13454-13455)
+ │       ├─14 WordNode[1] (397:149-397:154, 13455-13460)
+ 
  │       │   └─0 TextNode "Tweet" (397:149-397:154, 13455-13460)

+ 
```
to 
```diff
- │       ├─ SymbolNode "@"
- │       ├─ WordNode
- │       │   └─ TextNode "mentions"
- 
+ │       ├─ SourceNode "@mentions"
+ 
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode
  │       │   └─ TextNode "in"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode
  │       │   └─ TextNode "your"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode
  │       │   └─ TextNode "Tweet"
```

**Comment by ChristianMurphy** [comment]
Thanks @muescha, for the enthusiasm and sharing ideas!
I agree it would be valuable to have a utility to print positional information.
I've personally seen this plugin are more a way of prepresenting the AST, just the structure of the content.
This seems to be edging towards more of a CST type functionality, I'm wonder if this is a good fit for this util or if the approach may warrant it's own plugin.
Thoughts @syntax-tree/core?

**Comment by wooorm** [comment]
I want to second @ChristianMurphy in that the enthusiasm is appreciated!

Generally, I’d prefer to keep the number of options low, and indeed, it might make more sense as a different project.
I can somewhat see that `showIndex` might be useful: the previous version didn’t have it, the current behavior is a bit verbose.
Not so sure about `showChildCount` though.

**Comment by wooorm** [comment]
@muescha Any thoughts on how to proceed with @ChristianMurphy and my feedback?

**Comment by muescha** [comment]
## reduce diff noise with `showChildCount`

with `showPosition:false`  it reduced the noise to 


```diff
- │   └─2 SentenceNode[29]
- 
+ │   └─2 SentenceNode[28]
+ 
  │       ├─0 WordNode[1]
  │       │   └─0 TextNode "Make"
  │       ├─1 WhiteSpaceNode " "
  │       ├─2 WordNode[1]
  │       │   └─0 TextNode "sure"
  │       ├─3 WhiteSpaceNode " "
  │       ├─4 WordNode[1]
  │       │   └─0 TextNode "to"
  │       ├─5 WhiteSpaceNode " "
  │       ├─6 WordNode[1]
  │       │   └─0 TextNode "mention"
  │       ├─7 WhiteSpaceNode " "
  
- │       ├─8 SymbolNode "@"
- │       ├─9 WordNode[1]
- │       │   └─0 TextNode "mentions"
- │       ├─10 WhiteSpaceNode " "
- │       ├─11 WordNode[1]
- 
+ │       ├─8 SourceNode "@mentions"
+ │       ├─9 WhiteSpaceNode " "
+ │       ├─10 WordNode[1]
+ 
  │       │   └─0 TextNode "in"
  
- │       ├─12 WhiteSpaceNode " "
- │       ├─13 WordNode[1]
- 
+ │       ├─11 WhiteSpaceNode " "
+ │       ├─12 WordNode[1]
+ 
  │       │   └─0 TextNode "your"
  
- │       ├─14 WhiteSpaceNode " "
- │       ├─15 WordNode[1]
- 
+ │       ├─13 WhiteSpaceNode " "
+ │       ├─14 WordNode[1]
+ 
  │       │   └─0 TextNode "Tweet"

+ 
```


with `showPosition:false, showIndex:false`  it reduced the noise to this, but still the `SentenceNode` is diffed, because of `childCount`

```diff
- │   └─ SentenceNode[29]
- 
+ │   └─ SentenceNode[28]
+ 
  │       ├─ WordNode[1]
  │       │   └─ TextNode "Make"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode[1]
  │       │   └─ TextNode "sure"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode[1]
  │       │   └─ TextNode "to"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode[1]
  │       │   └─ TextNode "mention"
  │       ├─ WhiteSpaceNode " "
  
- │       ├─ SymbolNode "@"
- │       ├─ WordNode[1]
- │       │   └─ TextNode "mentions"
- │       ├─ WhiteSpaceNode " "
- │       ├─ WordNode[1]
- 
+ │       ├─ SourceNode "@mentions"
+ │       ├─ WhiteSpaceNode " "
+ │       ├─ WordNode[1]
+ 
  │       │   └─ TextNode "in"  
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode[1] 
  │       │   └─ TextNode "your"
  │       ├─ WhiteSpaceNode " "
  │       ├─ WordNode[1] 
  │       │   └─ TextNode "Tweet"

```

**Comment by muescha** [comment]
### Diff "problems"

for my use case with a diff - if a new node is replacing 3 nodes,
- then all the followup nodes in this tree are marked as changed, because of the position 
- the parent node is marked as changed, because of the child counter is changing.


### Too much options

i agree too much options are not that nice

i expected the behaviour `(showPositions: false, showIndex: false, showChildCount: false)` with the current `showPosition:true`
but when i hide the index and the child counter then it would change current behaviour 


### less option Solutions

maybe this solutions available:

#### a) all in `showPosition`

apply the changes from `showIndex: false, showChildCount: false` also to `showPosition`

pro: less options
con: not backward compatible

#### b) new options in one Option

apply the changes from `showIndex: false, showChildCount: false` in one option, i don't have a good name for it

pro: less options
con: -

#### c) only one new option `style`

introduce only a new option `style`

with options `full`, `plain`, or custom style as string

then templates are used
```javascript
{
    full: "${indent}{$index} ${type}${childCount} ${value} (${position})",
   plain: "${indent} ${type} ${value}"
}
```

`custom`: can be any template with this values:
`{ indent, index, type, childCount, value, data, position }` and additional a flat object `position`

pro: one option, very customizable
con: it feels somehow overengineered

### more options i like to have

i know you don't like to much options, but i like also to add the option:

`showDataPretty: true` (defaults to `false`)

to show the `data` with:

```diff
  function inspectNonTree(value) {
-    return JSON.stringify(value)
+    return showDataPretty ? JSON.stringify(value, null, 2) : JSON.stringify(value)
  }
```

if changes

```diff
+          1402: insert right: EmoticonNode "😉" (139:280-139:282, 5029-5031)
+                            >   data: {"emoji":"😉","description":"winking face","names":["wink"],"tags":["flirt"]}
-          1458: remove  left: EmoticonNode "😉" (139:280-139:282, 5029-5031)
```

to

```diff
+          1402: insert right: EmoticonNode "😉" (139:280-139:282, 5029-5031)
+                            >   data: {
+                            >     "emoji": "😉",
+                            >     "description": "winking face",
+                            >     "names": [
+                            >       "wink"
+                            >     ],
+                            >     "tags": [
+                            >       "flirt"
+                            >     ]
+                            >   }
-          1458: remove  left: EmoticonNode "😉" (139:280-139:282, 5029-5031)
```

### new package

i am personaly against to spread to much similar packages over npm. this makes hard to distinct which packege is better, and also introduce outdated packages if the `unist-util-inspect` becomes bugfixes. but if you decide it is worth to make a new package with this new options i am not against this. 

but then: what is the best name for this package (i am not good in naming things)? `unist-util-inspect-???`

**Comment by wooorm** [comment]
I’m going to close this as it seems it is neither accepted nor active. Maybe a new discussion for a smaller set of changes?

**Pull request closed without merging**
